//User
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';

//Authentication
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';
export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';
export const PASSWORD_INPUT_UPDATE = 'PASSWORD_INPUT_UPDATE';
export const GET_VERIFICATION_CODE = 'GET_VERIFICATION_CODE';
export const CODE_VERIFIED = 'CODE_VERIFIED';
export const ACTIVATE = 'ACTIVATE';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const DATA_REFRESH = 'DATA_REFRESH';
export const CLEAR_DATA_REFRESH = 'CLEAR_DATA_REFRESH';

//INPUT
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const INPUT_BLUR = 'INPUT_BLUR';

//REPORTS
export const REPORT_AVAILABLE = 'REPORT_AVAILABLE';
export const REPORT_NOT_AVAILABLE = 'REPORT_NOT_AVAILABLE';

//CERTIFICATES
export const GET_USER_CERTS = 'GET_USER_CERTS';
export const ADD_USER_CERT = 'ADD_USER_CERT';
export const GET_USER_CERTS_YEAR = 'GET_USER_CERTS_YEAR';
export const EDIT_CERT_COURSE = 'EDIT_CERT_COURSE';
export const DELETE_CERT_COURSE = 'DELETE_CERT_COURSE';

//NON-VERIAFIABLE
export const GET_USER_NONVER_YEAR = 'GET_USER_NONVER_YEAR';
export const GET_USER_NONVER = 'GET_USER_NONVER';
export const ADD_NONVER_SESSION = 'ADD_NONVER_SESSION';
export const EDIT_NONVER_SESSION = 'EDIT_NONVER_SESSION';
export const DELETE_NONVER_SESSION = 'DELETE_NONVER_SESSION';
