//User
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';

//Authentication
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';
export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';
export const PASSWORD_INPUT_UPDATE = 'PASSWORD_INPUT_UPDATE';

//INPUT
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const INPUT_BLUR = 'INPUT_BLUR';

//REPORTS
export const REPORT_AVAILABLE = 'REPORT_AVAILABLE';
export const REPORT_NOT_AVAILABLE = 'REPORT_NOT_AVAILABLE';

//CERTIFICATES
export const GET_USER_CERTS = 'GET_USER_CERTS';
export const GET_USER_CERTS_YEAR = 'GET_USER_CERTS_YEAR';
export const EDIT_CERT_COURSE = 'EDIT_CERT_COURSE';

//NON-VERIAFIABLE
export const GET_USER_NONVER_YEAR = 'GET_USER_NONVER_YEAR';
export const GET_USER_NONVER = 'GET_USER_NONVER';
export const ADD_NONVER_SESSION = 'ADD_NONVER_SESSION';
export const EDIT_NONVER_SESSION = 'EDIT_NONVER_SESSION';
